### ISSUE TITLE
Failed to install in Odoo13CE

### ISSUE THREAD

**Issue by pepitovadecurt** [kerolesayed/om-hospital#1]
Failed to install in Odoo13CE with these error:

`Odoo Server Error
Traceback (most recent call last):
  File "/home/user/Escriptori/odoo13/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/user/Escriptori/odoo13/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/user/Escriptori/odoo13/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f15430c4e50>, 'om_hospital.model_hospital_patient')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/Escriptori/odoo13/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/home/user/Escriptori/odoo13/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/home/user/Escriptori/odoo13/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/home/user/Escriptori/odoo13/odoo/tools/convert.py", line 561, in _tag_record
    f_val = self.id_get(f_ref)
  File "/home/user/Escriptori/odoo13/odoo/tools/convert.py", line 657, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/home/user/Escriptori/odoo13/odoo/tools/convert.py", line 663, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/home/user/Escriptori/odoo13/odoo/addons/base/models/ir_model.py", line 1681, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-24>", line 2, in xmlid_lookup
  File "/home/user/Escriptori/odoo13/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/user/Escriptori/odoo13/odoo/addons/base/models/ir_model.py", line 1670, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: om_hospital.model_hospital_patient

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/Escriptori/odoo13/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/user/Escriptori/odoo13/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/user/Escriptori/odoo13/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/user/Escriptori/odoo13/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/home/user/Escriptori/odoo13/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/user/Escriptori/odoo13/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/user/Escriptori/odoo13/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/user/Escriptori/odoo13/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/user/Escriptori/odoo13/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/user/Escriptori/odoo13/addons/web/controllers/main.py", line 1326, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/user/Escriptori/odoo13/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/user/Escriptori/odoo13/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/user/Escriptori/odoo13/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-59>", line 2, in button_immediate_install
  File "/home/user/Escriptori/odoo13/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/user/Escriptori/odoo13/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/user/Escriptori/odoo13/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/user/Escriptori/odoo13/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/user/Escriptori/odoo13/odoo/modules/loading.py", line 421, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/user/Escriptori/odoo13/odoo/modules/loading.py", line 313, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/user/Escriptori/odoo13/odoo/modules/loading.py", line 225, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/home/user/Escriptori/odoo13/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/user/Escriptori/odoo13/odoo/tools/convert.py", line 736, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/user/Escriptori/odoo13/odoo/tools/convert.py", line 803, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/user/Escriptori/odoo13/odoo/tools/convert.py", line 715, in parse
    pycompat.reraise(
  File "/home/user/Escriptori/odoo13/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/home/user/Escriptori/odoo13/odoo/tools/convert.py", line 712, in parse
    self._tag_root(de)
  File "/home/user/Escriptori/odoo13/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/home/user/Escriptori/odoo13/odoo/tools/convert.py", line 674, in _tag_root
    f(rec)
  File "/home/user/Escriptori/odoo13/odoo/tools/convert.py", line 561, in _tag_record
    f_val = self.id_get(f_ref)
  File "/home/user/Escriptori/odoo13/odoo/tools/convert.py", line 657, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/home/user/Escriptori/odoo13/odoo/tools/convert.py", line 663, in model_id_get
    return self.env['ir.model.data'].xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/home/user/Escriptori/odoo13/odoo/addons/base/models/ir_model.py", line 1681, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-24>", line 2, in xmlid_lookup
  File "/home/user/Escriptori/odoo13/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/user/Escriptori/odoo13/odoo/addons/base/models/ir_model.py", line 1670, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
odoo.tools.convert.ParseError: "External ID not found in the system: om_hospital.model_hospital_patient" while parsing /home/user/Escriptori/odoo13/addons_user/om-hospital-master/data/template_mail.xml:2, near
<odoo>

    <data noupdate="1">
        <record id="email_patient" model="mail.template">
            <field name="name">Patient: Send by email</field>
            <field name="model_id" ref="om_hospital.model_hospital_patient"/>
            <field name="email_from">${(object.user_id.email_formatted) |safe}</field>
            <field name="email_to">${object.email}</field>
            <field name="subject">Patient card (Ref ${object.name_sec})</field>
            <field name="body_html" type="html">
                    <div style="margin: 0px; padding: 0px;">
                        <p style="margin: 0px; padding: 0px; font-size: 13px;">
                            Dear
                                ${object.name}
                            <br/><br/>
                            here patient card
                            <br/><br/>
                            Do not hesitate to contact us if you have any questions.
                        </p>
                    </div>
                                </field>
                                <field name="report_template" ref="patient_card"/>
                                <field name="report_name">Patient Card_${(object.name_sec)}</field>
        </record>
    </data>
</odoo>`

**Comment by Alitux** [comment]
I Have the same Isssue. :(
